// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw53geak_8Gind8oUbbFnHg362OERzb5w',
    appId: '1:977485684850:web:ece8ae428b3952d31262eb',
    messagingSenderId: '977485684850',
    projectId: 'cmsc23-todo-app-zbduno',
    authDomain: 'cmsc23-todo-app-zbduno.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-zbduno.appspot.com',
    measurementId: 'G-53RCHG5P21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAynRndS8iG8ka6EVf5cub5ATnChPdJ968',
    appId: '1:977485684850:android:da7629f531a4fc451262eb',
    messagingSenderId: '977485684850',
    projectId: 'cmsc23-todo-app-zbduno',
    storageBucket: 'cmsc23-todo-app-zbduno.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdzCwePiXXV_-sP2FNmVLaA5dwLRvTvpo',
    appId: '1:977485684850:ios:6d6d437eee6aa7451262eb',
    messagingSenderId: '977485684850',
    projectId: 'cmsc23-todo-app-zbduno',
    storageBucket: 'cmsc23-todo-app-zbduno.appspot.com',
    iosClientId: '977485684850-3a5v2g3lf939635aj8kfdnbfmso8knso.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdzCwePiXXV_-sP2FNmVLaA5dwLRvTvpo',
    appId: '1:977485684850:ios:6d6d437eee6aa7451262eb',
    messagingSenderId: '977485684850',
    projectId: 'cmsc23-todo-app-zbduno',
    storageBucket: 'cmsc23-todo-app-zbduno.appspot.com',
    iosClientId: '977485684850-3a5v2g3lf939635aj8kfdnbfmso8knso.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
